#define MESSAGE_NOTICE 1
#define MESSAGE_WARNING 2
#define MESSAGE_DANGER 3

#define SOULCRYPT_ENERGY_PER_NUTRITION 5

#define NUTRITION_USAGE_LOW 1
#define NUTRITION_USAGE_MEDIUM 2
#define NUTRITION_USAGE_HIGH 3

#define ENERGY_WARNING_DELAY 45 SECONDS
#define INTEGRITY_WARNING_DELAY 5 MINUTES

#define SOULCRYPT_ONLINE 1
#define SOULCRYPT_LOW_POWER 2
#define SOULCRYPT_DISRUPTED 3


