// Syzygy's snowflake locker overrides

/obj/structure/closet/secure_closet/reinforced/captains/populate_contents()
	new /obj/item/weapon/storage/backpack/captain(src)
	new /obj/item/weapon/storage/backpack/satchel/captain(src)
	new /obj/item/clothing/head/caphat/cap(src)
	new /obj/item/clothing/under/rank/captain(src)
	new /obj/item/clothing/under/rank/captain_jumpskirt(src)
	new /obj/item/clothing/suit/armor/vest(src)
	new /obj/item/clothing/head/armor/helmet(src)
	new /obj/item/clothing/shoes/color/brown(src)
	new /obj/item/device/radio/headset/heads/captain(src)
	new /obj/item/clothing/gloves/captain(src)
	new /obj/item/weapon/gun/projectile/avasarala(src)
	new /obj/item/ammo_magazine/magnum/rubber(src)
	new /obj/item/ammo_magazine/magnum/rubber(src)
	new /obj/item/ammo_magazine/magnum/rubber(src)
	new /obj/item/ammo_magazine/magnum/rubber(src)
	new /obj/item/weapon/melee/telebaton(src)
	new /obj/item/clothing/head/caphat/formal(src)
	new /obj/item/clothing/under/captainformal(src)
	new /obj/random/cloth/holster(src)
	new /obj/item/clothing/suit/storage/captains_coat(src)

/obj/structure/closet/secure_closet/personal/miner/populate_contents()
	new /obj/item/weapon/storage/backpack/industrial(src)
	new /obj/item/weapon/storage/backpack/satchel/industrial(src)
	new /obj/item/device/radio/headset/headset_cargo(src)
	new /obj/item/clothing/under/rank/miner(src)
	new /obj/item/clothing/gloves/thick(src)
	new /obj/item/clothing/glasses/powered/meson(src)
	new /obj/item/clothing/shoes/black(src)
	new /obj/item/weapon/cell/medium(src)
	new /obj/item/weapon/cell/medium(src)
	new /obj/item/weapon/cell/small(src)
	new /obj/item/weapon/tool_upgrade/augment/fuel_tank(src)
	new /obj/item/device/scanner/gas(src)
	new /obj/item/weapon/storage/bag/ore(src)
	new /obj/item/device/lighting/toggleable/flashlight/heavy(src)
	new /obj/item/weapon/tool/shovel(src)
	new /obj/item/weapon/tool/pickaxe(src)
	new /obj/item/weapon/tool/pickaxe/drill(src)
	new /obj/item/weapon/gun/projectile/shotgun/leveraction(src)
	new /obj/item/weapon/storage/box/shotgunammo/slug(src)
	new /obj/item/device/t_scanner(src)